$(document).ready(function(){
    $(".s_login_page").owlCarousel({
        items:1,
        loop:true,
        dots:false,
        autoplay:true,
        autoplayTimeout:5000,
        autoplayHoverPause:true,
        smartSpeed:850,
        dragEndSpeed:500,
    });
});