//news slide
$(document).ready(function(){
    $(".s_main_category_slide").owlCarousel({
        items:1,
        loop:true,
        dots:false,
        autoplay:true,
        autoplayTimeout:5000,
        autoplayHoverPause:true,
        smartSpeed:850,
        dragEndSpeed:500,
    });
});

//Brands
$(document).ready(function(){
    $(".s_main_brand_slide").owlCarousel({
        loop:true,
        dots:false,
        autoplay:true,
        autoplayTimeout:2700,
        autoplayHoverPause:true,
        smartSpeed:350,
        dragEndSpeed:200,
        responsive:{
            0:{
                items:3,
            },
            767:{
                items:5,
            },
            1300:{
                items:7,
            }
        }
    });
});

//services
$(document).ready(function(){
    $(".s_services_show_label").owlCarousel({
        dots:false,
        autoplayTimeout:5000,
        autoplayHoverPause:true,
        smartSpeed:450,
        dragEndSpeed:200,
        responsive:{
            0:{
                items:1,
                autoplay:true,
                loop:true,
            },
            767:{
                items:2,
                autoplay:true,
                loop:true,
            },
            1300:{
                items:4,
            }
        }
    });
});

//Trends
$(document).ready(function(){
    $(".s_items").owlCarousel({
        dots:false,
        autoplayTimeout:6000,
        autoplayHoverPause:true,
        smartSpeed:450,
        dragEndSpeed:300,
        loop:true,
        autoplay:true,
        responsive:{
            0:{
                items:1,
                margin:0,
            },
            767:{
                items:2,
                margin:10,
            },
            1230:{
                items:3,
                margin:10,
            },
            1430:{
                items:4,
                margin:10,
            },
            1750:{
                items:5,
                margin:15,
            },
            2200:{
                items:6,
                margin:20,
            }
        }
    });
    // next prev duymeleri
    var owl = $('.s_items');
    owl.owlCarousel();
    $('.s_items_next').click(function() {
        owl.trigger('next.owl.carousel');
    });
    $('.s_items_prev').click(function() {
        owl.trigger('prev.owl.carousel', [300]);
    });
});